require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.3
  TargetRailsVersion: 7.1
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: ["describe", "context"]
  Exclude:
    - "config/routes.rb"

Layout/LineLength:
  Exclude:
    - "config/initializers/devise.rb"

RSpec/ExampleLength:
  Max: 40

RSpec/MultipleExpectations:
  Enabled: false

Rails/FilePath:
  Enabled: false

RSpec/ContextWording:
  Enabled: false
